### ISSUE TITLE
Geocoder PHP 

### ISSUE THREAD

**Issue by jbelien** [ici-brussels/urbis-php#1]
Would be awesome if you could include it as provider in https://github.com/geocoder-php/Geocoder :)

**Comment by ici-be** [comment]
Hello Jonathan, thanks for the tip ! I didn't know this tool existed...
I'll do my best to adapt my script and include it asap. I'll let you know !

Bruno

Le 5 nov. 2017 16:50, "Jonathan Beliën" <notifications@github.com> a écrit :

Would be awesome if you could include it as provider in
https://github.com/geocoder-php/Geocoder :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ici-brussels/urbis-php/issues/1>, or mute the thread

**Comment by ici-be** [comment]
... And same answer for the other geolocation class I begon this week-end
:) https://github.com/ici-brussels/bpost-addresses

**Comment by jbelien** [comment]
Awesome ! If you need some help, feel free to ask ! :)
I was planning to doing it but never had the time ^^

**Comment by jbelien** [comment]
Well, I took the time to do it : https://github.com/geo6/geocoder-php-urbis-provider.

I also created :
- https://github.com/geo6/geocoder-php-geopunt-provider
- https://github.com/geo6/geocoder-php-spw-provider

The 3 providers support geocoding (obviously) but also reverse geocoding !

And I'm currently developing the **bpost** provider :)
Feel free to use it !

PS: Happy new year 🎉

**Comment by jbelien** [comment]
bpost provider is now also available : https://github.com/geo6/geocoder-php-bpost-provider

**Comment by ici-be** [comment]
Hi Jonathan,
Thanks a lot, I'm looking forward to using these tools :)

I feel a bit ashamed of not having taken the time to try it by myself... As
soon as I have some time, I'll try to help where I can !

Happy New Year :)

Bruno
